// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB9Od33o4NKwhHnAj95lM9BRlnsO0kXSMk',
    appId: '1:429750940322:web:2a9622711a637b953e9dfb',
    messagingSenderId: '429750940322',
    projectId: 'love-space231223',
    authDomain: 'love-space231223.firebaseapp.com',
    storageBucket: 'love-space231223.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAHlWCE-2OGR_m5gZEQh_JW6j4WR_QNze0',
    appId: '1:429750940322:android:78e13702945a14483e9dfb',
    messagingSenderId: '429750940322',
    projectId: 'love-space231223',
    storageBucket: 'love-space231223.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDoFcVYNfTp6F5ld_-bLTG80IAor5E7Kuk',
    appId: '1:429750940322:ios:c00d373f15f1ca863e9dfb',
    messagingSenderId: '429750940322',
    projectId: 'love-space231223',
    storageBucket: 'love-space231223.firebasestorage.app',
    iosBundleId: 'com.maha.lovespace',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDoFcVYNfTp6F5ld_-bLTG80IAor5E7Kuk',
    appId: '1:429750940322:ios:c00d373f15f1ca863e9dfb',
    messagingSenderId: '429750940322',
    projectId: 'love-space231223',
    storageBucket: 'love-space231223.firebasestorage.app',
    iosBundleId: 'com.maha.lovespace',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB9Od33o4NKwhHnAj95lM9BRlnsO0kXSMk',
    appId: '1:429750940322:web:95bc4d7233dea93d3e9dfb',
    messagingSenderId: '429750940322',
    projectId: 'love-space231223',
    authDomain: 'love-space231223.firebaseapp.com',
    storageBucket: 'love-space231223.firebasestorage.app',
  );
}
